name: Build and release container

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - '**'
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - '**'
  workflow_dispatch:

jobs:
  container-build-push:
    uses: bbusse/github-workflows/.github/workflows/container-build-push.yaml@dev
    with:
      image_name: 'swayvnc-firefox'
      image_repository: 'ghcr.io/bbusse'
      #image_tags: ghcr.io/bbusse/swayvnc-firefox:${{ github.sha }},ghcr.io/bbusse/swayvnc-firefox:latest
      container_registry: 'ghcr'
      container_push_to_registry: true
